import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title} data-aos='fade-up' data-aos-delay='700'>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p
          className={styles.description}
          data-aos='fade-in'
          data-aos-delay='1000'
        >
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
          <ul>
            <li>
              🎃 User page {'=> '}
              <Link href='/users'>
                <a>
                  <code className={styles.code}>/users</code>
                </a>
              </Link>
            </li>
          </ul>
        </p>

        <div className={styles.grid}>
          <a
            href='https://nextjs.org/docs'
            className={styles.card}
            data-aos='fade-right'
            data-aos-delay='1300'
          >
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            href='https://nextjs.org/learn'
            className={styles.card}
            data-aos='fade-left'
            data-aos-delay='1400'
          >
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href='https://github.com/vercel/next.js/tree/canary/examples'
            className={styles.card}
            data-aos='fade-right'
            data-aos-delay='1500'
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}
            data-aos='fade-left'
            data-aos-delay='1600'
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
